### PR TITLE
Require cron recipe in default recipe.

### PR DESCRIPTION
**Pull request by dkinzer**
Some small CentOs installations do not come with cron by default. This
change helps ensure that a build does not fail because crontab is not
available.

### CODE REVIEW

**Comment by mdxp** [comment]
Merged. Thanks!

**Comment by dkinzer** [comment]
Thanks!

**Comment by mdxp** [comment]
btw, I made some quick fine tunings in 50d11cfb5ee3c947945e198c953c8c4540b9bda5 , mainly to keep foodcritic/travis happy ;).

**Comment by dkinzer** [comment]
Great, thanks.  I did notice it broke the travis test (I wasn't expecting that because I used code example from the opscode wiki for this qq).  Should I be running some specific test before doing a pull request?  Thanks!

**Comment by mdxp** [comment]
Just run `rake foodcritic` locally as this is the test travis will run also (nothing special at this time, only foodcritic but we will add more in the future).

**Pull request merged**
