### PR TITLE
Remote mysql and initial test-kitchen

### PR DESCRIPTION
**Pull request by gondoi**
This will allow the database to be on different server and commands to install will still work.

### CODE REVIEW

**Comment by gondoi** [comment]
Is there no need for remote databases, or is this being worked on elsewhere?

**Comment by mdxp** [comment]
I closed this based on your request and work on merging in #7

**Comment by gondoi** [comment]
Ah, sorry about that. I had forgotten the comments on my pull requests. :flushed:

**Comment by mdxp** [comment]
No worries. Sorry for the delay in taking care of this.

**Pull request closed without merging**
